### PR TITLE
Change thesis to dissertation based on toggle

### PR DESCRIPTION
**Pull request by jrleeman**
Per feedback from the graduate school, extend the effects of the toggle.

### CODE REVIEW

**Review by sonny-harman — APPROVED** [review]

**Comment by jrleeman** [comment]
Woot!

**Comment by sonny-harman** [comment]
I'm still new to pull requests - sorry it took me so long to see this one!

**Comment by jrleeman** [comment]
No worries - I had it locally, but wanted to save someone else a few rounds with the grad school editors. 😄

**Comment by sonny-harman** [comment]
I appear to have approved it, but not merged it? Like I said, new to pulls.

**Comment by jrleeman** [comment]
Ah, appears so. Reopen and then there should be merge button.

**Comment by sonny-harman** [comment]
Got it this time - sorry about that!

**Comment by jrleeman** [comment]
No worries!

**Pull request merged**
